# Generated by Django 4.2.11 on 2024-04-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='discount_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.discountrule'),
        ),
    ]
